home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('results/', views.artists_view, name='page_result'),
    path('results/<pk>/detail/', views.detail, name='detail'),
    path('results/<pk>/post_favorite/', views.post_favorite, name='fav'),
    path('results/<pk>/post_favorite_kartul/', views.post_favorite_kartul, name='fav2'),
    path('list_fav/', views.list_fav, name='list_fav'),
    path('profile/', views.AccountsSettings, name="profile"),


] 

pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('administration/', include('admin1.urls')),
    path('accounts/', include('account.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'account.views.handler404'
handler500 = 'account.views.handler500'

home/models.py

from django.db import models
from admin1.models import *
from django.contrib.auth.models import User


class ProfileUser(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    alamat = models.TextField(null=True)
    profile_pic = models.ImageField(upload_to="profile",default='defaultavatar.png',null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    def __str__(self):
        return str(self.name) if self.name else ''

home/forms.py
from django.forms import ModelForm
from .models import *
from home.forms import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
class LoginForm(UserCreationForm):
    class Meta:
         model = User
         fields = ['username', 'password1']

class ProfileUserForm2(ModelForm):
	class Meta:
		model = User
		fields = ['email']
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['email'].widget.attrs.update({ 'class': 'form-control rounded border-secondary','type':'email', 'placeholder':'Email..','name':'email' })


class ProfileUserForm(ModelForm):
    class Meta:
        model = ProfileUser
        exclude = ['email']
        widgets={
            'phone':forms.TextInput(attrs={'type':'number'})
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['alamat'].widget.attrs.update({ 'class': 'form-control', 'type': 'text' })
        self.fields['name'].widget.attrs.update({ 'class': 'form-control', 'type': 'text' })
        self.fields['profile_pic'].widget.attrs.update({ 'class': 'form-control', 'type': 'file' })
        self.fields['phone'].widget.attrs.update({ 'class': 'form-control', 'type': 'number'})

home/views.py
from http.client import HTTPResponse
from admin1.models import *
from admin1.forms import *
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Q 
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from itertools import chain

from home.forms import ProfileUserForm,ProfileUserForm2
def home(request):
    group = request.user.groups.first()
    if group is not None and group.name == 'admin':
        messages.success(request, 'Selamat Datang Admin')
        return HttpResponseRedirect('/administration/')
    elif group is not None and group.name == 'user':
        group = request.user.groups.first()
        return render(request, 'home.html', {
            # 'data':data,
        })
    else:
        return render(request, 'home.html', {
            # 'data':data,
        })
def detail(request, pk):
    post = UploadSkripsi.objects.filter(id=pk)
    post1 = Upload.objects.filter(id=pk)
    context = {
        'kartul':post1,
        'skripsi':post,
    }
    return render(request, 'details.html' ,context)



def artists_view(request):
    if 'q' in request.GET:
        query = request.GET['q']
        multiple_q = Q(judul_laporan__icontains=query) | Q(abstrak__icontains=query) | Q(nama_penulis__icontains=query) | Q(prodi__icontains=query) | Q(tahun_penyelesaian__icontains=query) | Q(nim_siswa__icontains=query)
        journal = Upload.objects.filter(multiple_q).order_by('-created_at')
        skripsi = UploadSkripsi.objects.filter(multiple_q).order_by('-created_at')
    else:
        journal = Upload.objects.all()
        skripsi = UploadSkripsi.objects.all()
    context ={
        'journal':journal,
        'skripsi':skripsi,
    }
    return render(request, 'page_result.html', context)


def post_favorite(request, pk):
    post1 = get_object_or_404(UploadSkripsi,id=pk)
    if post1.favourite.filter(pk=request.user.id).exists():
        post1.favourite.remove(request.user)
        messages.success(request,'Data telah dihapus')
    else:
        post1.favourite.add(request.user)
        messages.success(request,'Data telah ditambahkan')
    return HttpResponseRedirect('/list_fav/')

    
def post_favorite_kartul(request, pk):
    post2 = get_object_or_404(Upload,id=pk)
    if post2.favourite.filter(pk=request.user.id).exists():
        post2.favourite.remove(request.user)
        messages.success(request, 'bookmark telah dihapus')
    else:
        post2.favourite.add(request.user)
        messages.success(request, 'bookmark telah ditambahkan')
    return HttpResponseRedirect('/list_fav/')

@login_required(login_url='/accounts/')
def list_fav(request):
    user = request.user
    kartul = user.fav.all()
    skripsi = user.fav2.all()
    notfound = 'Data not Found'
    if kartul :
        kartul = user.fav.all()
        skripsi = user.fav2.all()
        context = {
        'journal':kartul,
        'skripsi':skripsi,
        }
        return render(request, 'bookmark.html', context)
    elif skripsi :
        skripsi = user.fav2.all()
        kartul = user.fav.all()
        context = {
        'journal':kartul,
        'skripsi':skripsi,
        }
        return render(request, 'bookmark.html', context)
    else:
        notfound = 'Data Tidak Ditemukan'
    context = {
        'journal':kartul,
        'skripsi':skripsi,
        'notfound':notfound,
    }
    return render(request, 'bookmark.html', context)



@login_required(login_url='/accounts/')
def AccountsSettings(request):
    user = ProfileUser.objects.filter(user=request.user).first()
    user2 = User.objects.filter(email=request.user.email).first()
    form = ProfileUserForm(instance=user)
    form2 = ProfileUserForm2(instance=user2)
    if request.POST:
        form = ProfileUserForm(request.POST, request.FILES, instance=user)
        form2 = ProfileUserForm2(request.POST, request.FILES, instance=user2)
        if form.is_valid() and form2.is_valid():
            form.instance.user = request.user
            form2.email = form2.cleaned_data['email']
            form.save()
            form2.save()
            messages.success(request, 'Data telah ditambahkan.')
            return redirect('/profile/')
        else:
            print(form.errors)
            print(form2.errors)
    else:
        form = ProfileUserForm(instance=user)
        form2 = ProfileUserForm2(instance=user2)

    context ={
        'form':form,
        'form2':form2,
    }
    return render(request, 'profile/index.html', context)


home/templates/bookmark.html
{% include "frontend/header.html" %}
{% load static %}
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo mr-5" href="/"><img src="{% static 'admin/inf.png' %}" class="mr-2"
        alt="logo" />Cerdas</a>
    <a class="navbar-brand brand-logo-mini" href="/"><img src="{% static 'admin/inf.png' %}" alt="logo" /></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="icon-menu"></span>
    </button>


    <ul class="navbar-nav mr-lg-2">
      <li class="nav-item nav-search d-none d-lg-block">
        <form action="/results/" method="get">
          <div class="input-group">
            <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
              <span class="input-group-text" id="search">
                <i class="icon-search"></i>
              </span>
            </div>
            <input type="text" name="q" class="form-control" id="navbar-search-input" placeholder="Cari Sekarang"
              aria-label="search" aria-describedby="search">
          </div>
        </form>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item">
        {{request.user.profileuser.name}}
      </li>
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
          {% if request.user.is_authenticated %}
          <img src="/media/{{ request.user.profileuser.profile_pic }}" alt="profile" />
          {% else %}
          <img src="{% static 'admin/defaultavatar.png' %}" alt="profile" />
          {% endif %}
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
          {% if request.user.is_authenticated %}
          <a class="dropdown-item" href="{% url 'home:list_fav' %}">
            <i class="fa-solid fa-bookmark" style="color: #7D9D9C;"></i>
            Bookmark
          </a>
          <a class="dropdown-item" href="{% url 'home:profile' %}">
            <i class="fa-solid fa-user-tie" style="color: #7D9D9C;"></i>
            Edit Profil
          </a>
          <a class="dropdown-item" href="{% url 'logout' %}">
            <i class="fa-sharp fa-solid fa-power-off" style="color: #7D9D9C;"></i>
            Keluar
          </a>
          {% else %}
          <a class="dropdown-item" href="{% url 'login' %}">
            <i class="fa-solid fa-right-to-bracket" style="color: #7D9D9C;"></i>
            Masuk
          </a>
          {% endif %}
        </div>
      </li>
    </ul>
  </div>
</nav>
<div class="container-fluid page-body-wrapper">
  <div class="main-panel" style="width: 100%;">
    {% include 'frontend/messages.html' %}
    <div class="content-wrapper" style="background-color: #dbe7c8;">
      <div class="row justify-content-center">
        {% for b in journal %}
        <div class="col-12 col-md-10 col-lg-8 stretch-card grid-margin">
          <div class="card">
            <div class="card-body shadow">
              <ul class="icon-data-list">
                <li>
                  <div class="d-flex">
                    <div> <a href="/results/{{b.pk}}/detail/">
                        <h5 class=" mb-2" style="color: #5f7667; font-weight: bold;">{{b.judul_laporan}}</h5>
                      </a>
                      <span class="text-secondary">{{b.nama_penulis}} ({{b.prodi}}, {{b.tahun_penyelesaian}})</span>
                      <p class="mb-1">{{b.abstrak}}</p>
                      {% for u in request.user.groups.all %}
                      {% if u.name == 'user' %}
                      <a href="/results/{{b.pk}}/post_favorite_kartul/" class="btn"><i class="fa-solid fa-bookmark"
                          style="color: #7D9D9C;"></i></a>
                      {% endif %}
                      {% endfor %}

                      <button type="button" class="btn" data-toggle="modal" data-target="#journal">
                        <i class="fa-solid fa-quote-right"></i>
                      </button>

                      <!-- Modal -->
                      <div class="modal fade" id="journal" tabindex="-1" role="dialog"
                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Daftar Pustaka</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <div class="container-fluid">
                                <div class="row">
                                  <div class="col-3">
                                    <b>MLA</b>
                                  </div>
                                  <div class="col-9">
                                    <h6 class="text-black">{{b.nama_penulis}}. "{{b.judul_laporan}}"
                                      <i>{{b.jenis_laporan}}</i> ({{b.tahun_penyelesaian}})
                                    </h6 class="text-black">
                                  </div>
                                </div>
                                <br>
                                <div class="row">
                                  <div class="col-3">
                                    <b>APA</b>
                                  </div>
                                  <div class="col-9">
                                    <h6 class="text-black">{{b.nama_penulis}}. ({{b.tahun_penyelesaian}}).
                                      "{{b.judul_laporan}}", <i>{{b.jenis_laporan}}</i></h6 class="text-black">
                                  </div>
                                </div>
                                <br>
                                <div class="row">
                                  <div class="col-3">
                                    <b>ISO 690</b>
                                  </div>
                                  <div class="col-9">
                                    <h6 class="text-black">{{b.nama_penulis}}. "{{b.judul_laporan}}"
                                      <i>{{b.jenis_laporan}}, </i>{{b.tahun_penyelesaian}}
                                    </h6 class="text-black">
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                          </div>
                        </div>
                      </div>

                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
        {% endfor %}
        {% for d in skripsi %}
        <div class="col-12 col-md-10 col-lg-8 stretch-card grid-margin">
          <div class="card">
            <div class="card-body shadow">
              <ul class="icon-data-list">
                <li>
                  <div class="d-flex">
                    <div> <a href="/results/{{d.pk}}/detail/">
                        <h5 class=" mb-2" style="color: #5f7667; font-weight: bold;">{{d.judul_laporan}}</h5>
                      </a>
                      <span class="text-secondary">{{d.nama_penulis}} ({{d.prodi}}, {{d.tahun_penyelesaian}})</span>
                      <p class="mb-1">{{d.abstrak}}</p>
                      {% for u in request.user.groups.all %}
                      {% if u.name == 'user' %}
                      <a href="/results/{{d.pk}}/post_favorite/" class="btn"><i class="fa-solid fa-bookmark"
                          style="color: #7D9D9C;"></i></a>
                      {% endif %}
                      {% endfor %}

                      <button type="button" class="btn" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa-solid fa-quote-right"></i>
                      </button>

                      <!-- Modal -->
                      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Daftar Pustaka</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <div class="container-fluid">
                                <div class="row">
                                  <div class="col-3">
                                    <b>MLA</b>
                                  </div>
                                  <div class="col-9">
                                    <h6 class="text-black">{{d.nama_penulis}}. "{{d.judul_laporan}}"
                                      <i>{{d.jenis_laporan}}</i> ({{d.tahun_penyelesaian}})
                                    </h6 class="text-black">
                                  </div>
                                </div>
                                <br>
                                <div class="row">
                                  <div class="col-3">
                                    <b>APA</b>
                                  </div>
                                  <div class="col-9">
                                    <h6 class="text-black">{{d.nama_penulis}}. ({{d.tahun_penyelesaian}}).
                                      "{{d.judul_laporan}}", <i>{{d.jenis_laporan}}</i></h6 class="text-black">
                                  </div>
                                </div>
                                <br>
                                <div class="row">
                                  <div class="col-3">
                                    <b>ISO 690</b>
                                  </div>
                                  <div class="col-9">
                                    <h6 class="text-black">{{d.nama_penulis}}. "{{d.judul_laporan}}"
                                      <i>{{d.jenis_laporan}}, </i>{{d.tahun_penyelesaian}}
                                    </h6 class="text-black">
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
        {% endfor %}
        {{notfound}}
      </div>
    </div>
    {% include 'frontend/footer.html' %}

home/templates/details.html
{% extends "frontend/base.html" %}
{% load static %}

{% block content %}
<div class="content-wrapper" style="background-color: #dbe7c8;">
    {% if skripsi %}
    {% for b in skripsi %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-10 col-lg-8">
                <div class="mb-3">
                    <h3 class="text-center" style="color: #5f7667; font-weight: bold;">{{b.judul_laporan}}</h3>
                </div>
                <div class="mb-3">
                    <h6 class="text-center text-secondary">{{b.nama_penulis}}, {{b.prodi}},
                        {{b.tahun_penyelesaian}}
                        {% for u in request.user.groups.all %}
                        {% if u.name == 'user' %}
                        <a href="/results/{{b.pk}}/post_favorite/" class="btn"><i class="fa-solid fa-bookmark"
                                style="color: #7D9D9C;"></i></a>
                        {% endif %}
                        {% endfor %}
                </div>
                </h6>
            </div>
            <div class="mb-0">
                <p class="text-center">
                    {{b.abstrak}}
                </p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-3">
                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <button class="nav-link active" id="v-pills-home-tab" data-toggle="pill" data-target="#v-pills-home"
                        type="button" role="tab" aria-controls="v-pills-home" aria-selected="true">COVER</button>
                    <br>
                    <button class="nav-link" id="v-pills-messages-tab" data-toggle="pill"
                        data-target="#v-pills-messages" type="button" role="tab" aria-controls="v-pills-messages"
                        aria-selected="false">DAFTAR
                        ISI</button>
                    <br>
                    <button class="nav-link" id="v-pills-bab1-tab" data-toggle="pill" data-target="#v-pills-bab1"
                        type="button" role="tab" aria-controls="v-pills-bab1" aria-selected="false">BAB I</button>
                    <br>
                    <button class="nav-link" id="v-pills-bab2-tab" data-toggle="pill" data-target="#v-pills-bab2"
                        type="button" role="tab" aria-controls="v-pills-bab2" aria-selected="false">BAB II</button>
                    <br>
                    <button class="nav-link" id="v-pills-bab3-tab" data-toggle="pill" data-target="#v-pills-bab3"
                        type="button" role="tab" aria-controls="v-pills-bab3" aria-selected="false">BAB III</button>
                    <br>
                    <button class="nav-link" id="v-pills-bab4-tab" data-toggle="pill" data-target="#v-pills-bab4"
                        type="button" role="tab" aria-controls="v-pills-bab4" aria-selected="false">BAB IV</button>
                    <br>
                    <button class="nav-link" id="v-pills-bab5-tab" data-toggle="pill" data-target="#v-pills-bab5"
                        type="button" role="tab" aria-controls="v-pills-bab5" aria-selected="false">BAB V</button>
                    <br>
                    <button class="nav-link" id="v-pills-dapus-tab" data-toggle="pill" data-target="#v-pills-dapus"
                        type="button" role="tab" aria-controls="v-pills-dapus" aria-selected="false">DAFTAR
                        PUSTAKA</button>
                    <br>
                    <button class="nav-link" id="v-pills-lampiran-tab" data-toggle="pill"
                        data-target="#v-pills-lampiran" type="button" role="tab" aria-controls="v-pills-lampiran"
                        aria-selected="false">LAMPIRAN</button>
                    <br>
                </div>
            </div>
            <div class="col-9">
                <div class="tab-content" id="v-pills-tabContent">
                    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel"
                        aria-labelledby="v-pills-home-tab">
                        <a href="{{b.cover.url}}" download style="color: #5f7667; font-weight: bold; float: right;"><i
                                class="fa-solid fa-file-pdf"></i>Unduh Cover</a>
                        <div class="embed-responsive embed-responsive-4by3">
                            <iframe class="embed-responsive-item" type="application/pdf" src="{{b.cover.url}}" allowfullscreen></iframe>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-messages" role="tabpanel"
                        aria-labelledby="v-pills-messages-tab">
                        <a href="{{b.daftarisi.url}}" download
                            style="color: #5f7667; font-weight: bold; float: right;"><i
                                class="fa-solid fa-file-pdf"></i>Unduh Daftar Isi</a>
                        <div class="embed-responsive embed-responsive-4by3">
                            <iframe class="embed-responsive-item" src="{{b.daftarisi.url}}" allowfullscreen></iframe>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-bab1" role="tabpanel" aria-labelledby="v-pills-bab1-tab">
                        <a href="{{b.bab1.url}}" download style="color: #5f7667; font-weight: bold; float: right;"><i
                                class="fa-solid fa-file-pdf"></i>Unduh BAB I</a>
                        <div class="embed-responsive embed-responsive-4by3">
                            <iframe class="embed-responsive-item" src="{{b.bab1.url}}" allowfullscreen></iframe>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-bab2" role="tabpanel" aria-labelledby="v-pills-bab2-tab">
                        <a href="{{b.bab2.url}}" download style="color: #5f7667; font-weight: bold; float: right;"><i
                                class="fa-solid fa-file-pdf"></i>Unduh BAB II</a>
                        <div class="embed-responsive embed-responsive-4by3">
                            <iframe class="embed-responsive-item" src="{{b.bab2.url}}" allowfullscreen></iframe>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-bab3" role="tabpanel" aria-labelledby="v-pills-bab3-tab">
                        <a href="{{b.bab3.url}}" download style="color: #5f7667; font-weight: bold; float: right;"><i
                                class="fa-solid fa-file-pdf"></i>Unduh BAB III</a>
                        <div class="embed-responsive embed-responsive-4by3">
                            <iframe class="embed-responsive-item" src="{{b.bab3.url}}" allowfullscreen></iframe>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-bab4" role="tabpanel" aria-labelledby="v-pills-bab4-tab">
                        <!-- <a href="{{b.bab4.url}}" download style="color: #5f7667; font-weight: bold; float: right;"><i
                                class="fa-solid fa-file-pdf"></i>Unduh BAB IV</a> -->
                        <h5 class="text-center">Hubungi staf</h5>
                    </div>
                    <div class="tab-pane fade" id="v-pills-ba5" role="tabpanel" aria-labelledby="v-pills-ba5-tab">
                        <!-- <a href="{{b.bab5.url}}" download style="color: #5f7667; font-weight: bold; float: right;"><i
                                class="fa-solid fa-file-pdf"></i>Unduh BAB V</a> -->
                        <h5 class="text-center">Hubungi Staf</h5>
                    </div>
                    <div class="tab-pane fade" id="v-pills-dapus" role="tabpanel" aria-labelledby="v-pills-dapus-tab">
                        <a href="{{b.dapus.url}}" download style="color: #5f7667; font-weight: bold; float: right;"><i
                                class="fa-solid fa-file-pdf"></i>Unduh Daftar Pustaka</a>
                        <div class="embed-responsive embed-responsive-4by3">
                            <iframe class="embed-responsive-item" src="{{b.dapus.url}}" allowfullscreen></iframe>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-lampiran" role="tabpanel" aria-labelledby="v-pills-bab5-tab">
                        <a href="{{b.lampiran.url}}" download
                            style="color: #5f7667; font-weight: bold; float: right;"><i
                                class="fa-solid fa-file-pdf"></i>Unduh Lampiran</a>
                        <div class="embed-responsive embed-responsive-4by3">
                            <iframe class="embed-responsive-item" src="{{b.lampiran.url}}" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% elif kartul %}
    {% for b in kartul %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-10 col-lg-8">
                <div class="mb-3">
                    <h3 class="text-center" style="color: #5f7667; font-weight: bold;">{{b.judul_laporan}}</h3>
                </div>
                <div class="mb-3">
                    <h6 class="text-center text-secondary">{{b.nama_penulis}}, {{b.prodi}},
                        {{b.tahun_penyelesaian}}
                        {% for u in request.user.groups.all %}
                        {% if u.name == 'user' %}
                        <a href="/results/{{b.pk}}/post_favorite_kartul/" class="btn"><i class="fa-solid fa-bookmark"
                                style="color: #7D9D9C;"></i></a>
                        {% endif %}
                        {% endfor %}
                    </h6>
                </div>
                <div class="mb-0">
                    <p class="text-center">
                        {{b.abstrak}}
                    </p>
                </div>
                <div class="mb-3 text-center">
                    <a href="{{b.upload.url}}" download style="color: #5f7667; font-weight: bold;"><i
                            class="fa-solid fa-file-pdf"></i> Unduh
                        Files</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-10 col-lg-8">
                <div class="embed-responsive embed-responsive-4by3">
                    <iframe class="embed-responsive-item" src="{{b.upload.url}}" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<p>Data not found.</p>
{% endif %}
</div>


<!-- <div class="col-2"></div> -->
{% endblock %}