admin1/urls.py
from django.urls import path
app_name = 'administration'

from . import views
urlpatterns = [
    path('', views.index, name='admin'),
    path('profile/', views.AccountsSettings, name="profile"),
    path('mhs/', views.ListMhs, name='mhs'),
    path('mhs/<pk>/', views.DetailMhs, name='detail_mhs'),
    path('journal/', views.ListJournal, name='journal'),
    path('journal/create/', views.CreateJournal, name='create_journal'),
    path('journal/detail/<pk>/', views.DetailJournal, name='detail_journal'),
    path('journal/update/<pk>/', views.UpdateJournal, name='update_journal'),
    path('journal/delete/<pk>/', views.DeleteJournal, name='delete_journal'),
    path('skripsi/', views.ListSkripsi, name='skripsi'),
    path('skripsi/create/', views.CreateSkrispi, name='create_skripsi'),
    path('skripsi/update/<pk>/', views.UpdateSkripsi, name='update_skripsi'),
    path('skripsi/delete/<pk>/', views.DeleteSkrispi, name='delete_skripsi'),
    path('skripsi/detail/<pk>/', views.DetailSkripsi, name='detail_skripsi'),
] 

pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('administration/', include('admin1.urls')),
    path('accounts/', include('account.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'account.views.handler404'
handler500 = 'account.views.handler500'

admin1/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from home.models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class LoginForm(UserCreationForm):
    class Meta:
         model = User
         fields = ['username', 'password1']
         
class UploadForm(ModelForm):
    class Meta:
         model = Upload
         exclude = ['owner','favourite']
         widgets = {
            'judul_laporan': forms.TextInput({'class': 'form-control form-control-sm', 'type':'text','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
            'tahun_penyelesaian': forms.TextInput({'class': 'form-control form-control-sm', 'type':'number','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
            'abstrak': forms.Textarea({'class': 'form-control form-control-sm', 'type':'text','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
            'nama_penulis': forms.TextInput({'class': 'form-control form-control-sm', 'type':'text','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
            'nim_siswa': forms.TextInput({'class': 'form-control form-control-sm', 'type':'number','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
            'prodi': forms.Select({'class': 'form-control form-control-sm', 'type':'text','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
        }
    def __init__(self, *args, **kwargs):
        super(UploadForm, self).__init__(*args, **kwargs)
        self.fields['prodi'].initial = 'Select Prodi ...'
        self.fields['upload'].widget.attrs.update({ 'class': 'form-control file-upload-info','type':'file', 'accept':'application/pdf','style':'padding:6px 10px ;border: 1px solid #ced4da','placeholder':'{{data.upload.value}}'})
class UploadSkripsiForm(ModelForm):
    class Meta:
         model = UploadSkripsi
         exclude = ['owner','favourite']
         widgets = {
            'judul_laporan': forms.TextInput({'class': 'form-control form-control-sm', 'type':'text','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
            'tahun_penyelesaian': forms.TextInput({'class': 'form-control form-control-sm', 'type':'number','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
            'abstrak': forms.Textarea({'class': 'form-control form-control-sm', 'type':'text','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
            'nama_penulis': forms.TextInput({'class': 'form-control form-control-sm', 'type':'text','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
            'nim_siswa': forms.TextInput({'class': 'form-control form-control-sm', 'type':'number','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
            'prodi': forms.Select({'class': 'form-control form-control-sm', 'type':'text','style':'padding:6px 10px ;border: 1px solid #ced4da'}),
        }
    def __init__(self, *args, **kwargs):
        super(UploadSkripsiForm, self).__init__(*args, **kwargs)
        self.fields['prodi'].empty_label = 'Select Prodi ...'
        self.fields['lampiran'].widget.attrs.update({ 'class': 'form-control','type':'file', 'accept':'application/pdf','style':'padding:6px 10px ;border: 1px solid #ced4da'})
        self.fields['cover'].widget.attrs.update({ 'class': 'form-control','type':'file', 'accept':'application/pdf','style':'padding:6px 10px ;border: 1px solid #ced4da'})
        self.fields['daftarisi'].widget.attrs.update({ 'class': 'form-control','type':'file', 'accept':'application/pdf','style':'padding:6px 10px ;border: 1px solid #ced4da'})
        self.fields['bab1'].widget.attrs.update({ 'class': 'form-control','type':'file', 'accept':'application/pdf','style':'padding:6px 10px ;border: 1px solid #ced4da'})
        self.fields['bab2'].widget.attrs.update({ 'class': 'form-control','type':'file', 'accept':'application/pdf','style':'padding:6px 10px ;border: 1px solid #ced4da'})
        self.fields['bab3'].widget.attrs.update({ 'class': 'form-control','type':'file', 'accept':'application/pdf','style':'padding:6px 10px ;border: 1px solid #ced4da'})
        self.fields['bab4'].widget.attrs.update({ 'class': 'form-control','type':'file', 'accept':'application/pdf','style':'padding:6px 10px ;border: 1px solid #ced4da'})
        self.fields['bab5'].widget.attrs.update({ 'class': 'form-control','type':'file', 'accept':'application/pdf','style':'padding:6px 10px ;border: 1px solid #ced4da'})
        self.fields['dapus'].widget.attrs.update({ 'class': 'form-control','type':'file', 'accept':'application/pdf','style':'padding:6px 10px ;border: 1px solid #ced4da'})
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ['email']
        widgets={
            'phone':forms.TextInput(attrs={'type':'number'})
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['alamat'].widget.attrs.update({ 'class': 'form-control', 'type': 'text' })
        self.fields['name'].widget.attrs.update({ 'class': 'form-control', 'type': 'text' })
        self.fields['profile_pic'].widget.attrs.update({ 'class': 'form-control', 'type': 'file' })
        self.fields['phone'].widget.attrs.update({ 'class': 'form-control', 'type': 'number'})
class ProfileForm2(ModelForm):
	class Meta:
		model = User
		fields = ['email']
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['email'].widget.attrs.update({ 'class': 'form-control rounded border-secondary','type':'email', 'placeholder':'Email..','name':'email' })


def form_validation_error(form):
    msg = ""
    for field in form:
        for error in field.errors:
            msg += "%s: %s \\n" % (field.label if hasattr(field, 'label') else 'Error', error)
    return msg

admin1/views.py
from urllib import request
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from home.models import ProfileUser
import os
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Count

######################################## DASHBOARD #####################################

@login_required(login_url='/accounts/')
def index(request):
    skripsi = UploadSkripsi.objects.filter(owner=request.user)
    karlis = Upload.objects.filter(owner=request.user)
    profile = ProfileUser.objects.all()
    context ={'data':len(skripsi),'karlis':len(karlis), 'user':len(profile)}
    return render(request,"index.html", context)

######################################## SKRIPSI #####################################
@login_required(login_url='/accounts/')
def ListMhs(request):
    profile = ProfileUser.objects.all()
    return render(request, 'mhs/index.html',{
        'profile': profile,
        
    })
@login_required(login_url='/accounts/')
def DetailMhs(req, pk):
    data = ProfileUser.objects.filter(id=pk).first()
    return render(req, 'mhs/detail.html', {"data":data})
@login_required(login_url='/accounts/')
def ListJournal(request):
    tasks = Upload.objects.filter(owner=request.user)
    form_input = UploadForm()
    if request.POST:
        form_input = UploadForm(request.POST, request.FILES)
        if form_input.is_valid():
            form_input.instance.owner = request.user
            form_input.save()
            messages.success(request, 'Data telah ditambahkan.')
            return redirect('/administration/journal/')
        else:
            messages.error(request, 'A problem has been occurred while submitting your data.')
            print(form_input.errors)
    return render(request, 'journal/index.html',{
        'form' : form_input,
        'data': tasks,
        
    })

@login_required(login_url='/accounts/')
def CreateJournal(request):
    form_input = UploadForm()
    if request.POST:
        form_input = UploadForm(request.POST, request.FILES)
        if form_input.is_valid():
            form_input.instance.owner = request.user
            form_input.save()
            messages.success(request, 'Data telah ditambahkan.')
            return redirect('/administration/journal/')
        else:
            print(form_input.errors)
    else:
        form_input = UploadForm()
    context ={
        'form':form_input
    }
    return render(request, 'journal/create.html', context)
@login_required(login_url='/accounts/')
def UpdateJournal(request, pk):
    instance =get_object_or_404(Upload,id=pk)
    form_journal = UploadForm(instance=instance)
    if request.POST:
        form_journal = UploadForm(request.POST, request.FILES,instance=instance)
        if form_journal.is_valid():
            form_journal.owner = request.user
            form_journal.save()
            messages.success(request, "Data Telah diupdate")
            return redirect('/administration/journal/')
    context = {"data":form_journal}
    return render(request, 'journal/update.html', context) 

@login_required(login_url='/accounts/')
def DeleteJournal(req, pk):
    Upload.objects.get(id=pk).delete()
    messages.success(req, 'data telah di hapus.')
    return redirect('/administration/journal/')

@login_required(login_url='/accounts/')
def DetailJournal(req, pk):
    data = Upload.objects.filter(id=pk).first()
    return render(req, 'journal/detail.html', {"data":data})

######################################## SKRIPSI #####################################
@login_required(login_url='/accounts/')
def ListSkripsi(request):
    tasks = UploadSkripsi.objects.filter(owner=request.user)
    return render(request, 'skripsi/index.html',{
        'data': tasks,
        
    })
def CreateSkrispi(request):
    form_input = UploadSkripsiForm()
    if request.POST:
        form_input = UploadSkripsiForm(request.POST, request.FILES)
        if form_input.is_valid():
            form_input.instance.owner = request.user
            form_input.save()
            messages.success(request, 'Data telah ditambahkan.')
            return redirect('/administration/skripsi/')
    else:
        form_input = UploadSkripsiForm()
    context ={
        'form':form_input
    }
    return render(request, 'skripsi/create.html', context)
@login_required(login_url='/accounts/')
def UpdateSkripsi(request, pk):
    instance =get_object_or_404(UploadSkripsi,id=pk)
    form_skripsi = UploadSkripsiForm(instance=instance)
    if request.POST:
        form_skripsi = UploadSkripsiForm(request.POST, request.FILES,instance=instance)
        if form_skripsi.is_valid():
            form_skripsi.owner = request.user
            form_skripsi.save()
            messages.success(request, "Data Telah diupdate")
            return redirect('/administration/skripsi/')
    context = {"data":form_skripsi} 
    return render(request, 'skripsi/update.html', context) 
    
@login_required(login_url='/accounts/')
def DeleteSkrispi(req, pk):
    UploadSkripsi.objects.get(id=pk).delete()
    messages.success(req, 'data telah di hapus.')
    return redirect('/administration/skripsi/')

@login_required(login_url='/accounts/')
def DetailSkripsi(req, pk):
    data = UploadSkripsi.objects.filter(id=pk).first()
    return render(req, 'skripsi/detail.html', {"data":data})

@login_required(login_url='/accounts/')
def AccountsSettings(request):
    user = Profile.objects.filter(user=request.user).first()
    user2 = User.objects.filter(email=request.user.email).first()
    form = ProfileForm(instance=user)
    form2 = ProfileForm2(instance=user2)
    if request.POST:
        form = ProfileForm(request.POST, request.FILES, instance=user)
        form2 = ProfileForm2(request.POST, request.FILES, instance=user2)
        if form.is_valid() and form2.is_valid():
            form.instance.user = request.user
            form2.email = form2.cleaned_data['email']
            form.save()
            form2.save()
            messages.success(request, 'Data telah ditambahkan.')
            return redirect('/administration/profile/')
        else:
            print(form.errors)
            print(form2.errors)
    else:
        form = ProfileForm(instance=user)
        form2 = ProfileForm2(instance=user2)
    context ={
        'form_admin':form,
        'form_admin2':form2,
    }
    return render(request, 'profile/profile.html', context)


admin1/templates/journal/create.html
{% extends 'administration/base.html' %}
{% block content %}
<form class="forms-sample" method="post" enctype="multipart/form-data">
    {% load crispy_forms_tags %}
    {% csrf_token %}
    <div class="content-wrapper" style="background-color: #dbe7c8;">
        <div class="row">
            <div class="col-md-12 grid-margin">
                <div class="row">
                    <div class="col-12 col-xl-8 mb-4 mb-xl-0">
                        <h3 class="font-weight-bold">Tambah Skripsi</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label class="form-label">Nama Penulis</label>
                            {{form.nama_penulis}}
                        </div>
                        <div class="mb-3 col-md-6">
                            <label class="form-label">Judul Skripsi</label>
                            {{form.judul_laporan}}
                        </div>
                        <div class="mb-3 col-md-6">
                            <label class="form-label">NIM </label>
                            {{form.nim_siswa}}
                        </div>
                        <div class="mb-3 col-md-6">
                            <label class="form-label">Tahun</label>
                            {{form.tahun_penyelesaian}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group mb-3 col-md-12">
                            <label>Abstrak</label>
                            {{form.abstrak}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label class="form-label">Prodi</label>
                            {{form.prodi}}

                        </div>
                        <div class="form-group mb-3 col-md-6">
                            <label>Files</label>
                            <div class="input-group col-xs-12">
                                {{form.upload}}
                                <span class="input-group-append">
                                    <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
                                </span>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="col-12 d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
</form>
{% endblock %}

admin1/templates/journal/detail.html
{% extends 'administration/base.html' %}
{% block content %}
<div class="content-wrapper" style="background-color: #dbe7c8;">
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="row">
                <div class="col-12 col-xl-8 mb-4 mb-xl-0">
                    <h3 class="font-weight-bold">Data Jurnal</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-responsive col-md-10" id="" width="100%" cellspacing="0">
                            <thead>
                              <tr>
                                <td>Nama Penulis</td>
                                <td>:</td>
                                <td>{{data.nama_penulis}}</td>
                              </tr>
                              <tr>
                                <td>NIM Mahasiswa</td>
                                <td>:</td>
                                <td>{{data.nim_siswa}}</td>
                              </tr>
                              <tr>
                                <td>Judul Jurnal</td>
                                <td>:</td>
                                <td>{{data.judul_laporan}}</td>
                              </tr>
                              <tr>
                                <td>Tahun</td>
                                <td>:</td>
                                <td>{{data.tahun_penyelesaian}}</td>
                              </tr>
                              <tr>
                                <td>Abstrak</td>
                                <td>:</td>
                                <td>{{data.abstrak}}</td>
                              </tr>
                              <tr>
                                <td>File Jurnal</td>
                                <td>:</td>
                                <td><a style="color:#9C0000"  href="{{data.upload.url}}" download="file.pdf"><i class="fa-solid fa-file-pdf fa-2xl"></i></a></td>
                              </tr>
                              <tr>
                                <td>Tanggal Upload</td>
                                <td>:</td>
                                <td>{{data.created_at}}</td>
                              </tr>
                            </thead>
                          </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

admin1/templates/journal/index.html
{% extends 'administration/base.html' %}
{% block content %}
<div class="content-wrapper" style="background-color: #dbe7c8;">
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="row">
                <div class="col-12 col-xl-8 mb-4 mb-xl-0">
                    <h3 class="font-weight-bold">Data Jurnal</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <a type="button" class="btn btn-primary rounded-pill" style="float: right;" href="{% url 'administration:create_journal' %}">
                        Tambah Data
                    </a>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Nama Penulis</th>
                                    <th>Nim Mahasiswa</th>
                                    <th>Prodi</th>
                                    <th>Judul Jurnal</th>
                                    <th>Tanggal </th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            {% for u in data %}
                            <tbody>
                                <tr>
                                    <td>{{u.nama_penulis}}</td>
                                    <td>{{u.nim_siswa}}</td>
                                    <td>{{u.prodi}}</td>
                                    <td>{{u.judul_laporan}}</td>
                                    <td>{{u.created_at}}</td>
                                    <td>
                                        <a type="button" class="btn btn-primary"
                                            href="/administration/journal/detail/{{u.pk}}/"><i class="fas fa-eye"></i></a>

                                        <a type="button" class="btn btn-warning"
                                            href="/administration/journal/update/{{u.pk}}/"><i class="fas fa-regular fa-pen text-white"></i></a>
                                        <a type="button" class="btn btn-danger" data-toggle="modal"
                                            data-target="#delete-{{d.id}}">
                                            <i class="fas fa-trash-alt"></i></a>

                                    </td>
                                </tr>
                            </tbody>
                            <div class="modal fade" id="delete-{{d.id}}" tabindex="-1" role="dialog"
                                aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="delete">Delete Data Jurnal</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                                <p> Do You want To delete
                                                    <strong>{{d.id}}</strong>?
                                                </p>
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn" type="button" data-dismiss="modal" aria-label="Close">
                                                No
                                            </button>
                                            <a href="/administration/journal/delete/{{u.pk}}/" type="submit"
                                                class="btn btn-danger">Yes</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}

                        </table>

                        <!-- Modal Input -->
                        <div class="modal fade" id="input" tabindex="-1" role="dialog"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Tambah data</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form method="post" class="mt-3" enctype="multipart/form-data">
                                            {% load crispy_forms_tags %}
                                            {% csrf_token %}
                                            {{ form|crispy }}
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                    data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Save changes</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

admin1/templates/journal/update.html
{% extends 'administration/base.html' %}
{% block content %}
<div class="content-wrapper" style="background-color: #dbe7c8;">
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="row">
                <div class="col-12 col-xl-8 mb-4 mb-xl-0">
                    <h3 class="font-weight-bold">Edit Skripsi</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label class="form-label">Nama Penulis</label>
                            {{data.nama_penulis}}
                        </div>
                        <div class="mb-3 col-md-6">
                            <label class="form-label">Judul Skripsi</label>
                            {{data.judul_laporan}}
                        </div>
                        <div class="mb-3 col-md-6">
                            <label class="form-label">NIM </label>
                            {{data.nim_siswa}}"
                        </div>
                        <div class="mb-3 col-md-6">
                            <label class="form-label">Tahun</label>
                            {{data.tahun_penyelesaian}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label>Prodi</label>
                            {{data.prodi}}
                        </div>
                        <div class="form-group mb-3 col-md-6">
                            <label>File Jurnal</label>
                            {{data.upload}}
                            <small>File harus berbentuk PDF</small>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group mb-3 col-md-12">
                            <label>Abstrak</label>
                            {{data.abstrak}}
                        </div>
                    </div>
                    <div class="col-12 d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}