admin1/urls.py
from django.urls import path
app_name = 'administration'

from . import views
urlpatterns = [
    path('', views.index, name='admin'),
    path('profile/', views.AccountsSettings, name="profile"),
    path('mhs/', views.ListMhs, name='mhs'),
    path('mhs/<pk>/', views.DetailMhs, name='detail_mhs'),
    path('journal/', views.ListJournal, name='journal'),
    path('journal/create/', views.CreateJournal, name='create_journal'),
    path('journal/detail/<pk>/', views.DetailJournal, name='detail_journal'),
    path('journal/update/<pk>/', views.UpdateJournal, name='update_journal'),
    path('journal/delete/<pk>/', views.DeleteJournal, name='delete_journal'),
    path('skripsi/', views.ListSkripsi, name='skripsi'),
    path('skripsi/create/', views.CreateSkrispi, name='create_skripsi'),
    path('skripsi/update/<pk>/', views.UpdateSkripsi, name='update_skripsi'),
    path('skripsi/delete/<pk>/', views.DeleteSkrispi, name='delete_skripsi'),
    path('skripsi/detail/<pk>/', views.DetailSkripsi, name='detail_skripsi'),
] 

pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('administration/', include('admin1.urls')),
    path('accounts/', include('account.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'account.views.handler404'
handler500 = 'account.views.handler500'

templates/administration/base.html
{% load static %}
{% include "administration/header.html" %}
{% include "administration/sidebar.html" %}
<div class="main-panel">
  {% include 'administration/messages.html' %}
  {% block content %}
  {% endblock %}
  {% include "administration/footer.html" %}
</div>

templates/administration/footer.html
{% load static %}
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2022. Farros Hanifah</span>
  </div>
</footer>

<script>
  setTimeout(function () {
      if ($('#msg').length > 0) {
          $('#msg').remove();
      }
  }, 2000)
</script>
<!-- plugins:js -->
<script src="{% static 'admin/template/vendors/js/vendor.bundle.base.js' %}"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<script src="{% static 'admin/template/vendors/chart.js/Chart.min.js' %}"></script>
<!-- <script src="{% static 'admin/template/vendors/datatables.net/jquery.dataTables.js' %}"></script> --> 
<!-- <script src="{% static 'admin/template/vendors/datatables.net-bs4/dataTables.bootstrap4.js' %}"></script> -->
<script src="{% static 'admin/template/js/dataTables.select.min.js' %}"></script>

<script src="{% static 'admin/template/js/off-canvas.js' %}"></script>
<script src="{% static 'admin/template/js/hoverable-collapse.js' %}"></script>
<script src="{% static 'admin/template/js/template.js' %}"></script>
<script src="{% static 'admin/template/js/settings.js' %}"></script>
<script src="{% static 'admin/template/js/todolist.js' %}"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="{% static 'admin/template/js/dashboard.js' %}"></script>
<script src="{% static 'admin/template/js/Chart.roundedBarCharts.js' %}"></script>

<script src="{% static 'admin/template/js/file-upload.js' %}"></script>
<script src="{% static 'admin/template/js/typeahead.js' %}"></script>
<script src="{% static 'admin/template/js/select2.js' %}"></script>
<!-- End custom js for this page-->
</body>

</html>

templates/administration/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Repopsitory FTI</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">

  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'admin/template/vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'admin/template/vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'admin/template/vendors/font-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'admin/template/vendors/css/vendor.bundle.base.css' %}">
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'admin/template/css/vertical-layout-light/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'admin/inf.png' %}" />
</head>

<body>
  <div class="container-scroller">

templates/administration/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
        {{ message }}
    </div>
    {% endfor %}
 {% endif %}
        

templates/administration/sidebar.html
{% load static %}
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo mr-5" href="/administration"><img src="{% static 'admin/inf.png' %}" class="mr-2"
        alt="logo" />Cerdas</a>
    <a class="navbar-brand brand-logo-mini" href="/administration"><img src="{% static 'admin/inf.png' %}"
        alt="logo" /></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="icon-menu"></span>
    </button>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item">
        {{request.user.profile.name}}
      </li>
      <li class="nav-item nav-profile dropdown">
        {% if request.user.profile %}
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
          <img src="/media/{{ request.user.profile.profile_pic }}" alt="profile" />
        </a>
        {% else %}
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
          <img src="{% static 'admin/defaultavatar.png' %}" alt="profile" />
        </a>
        {% endif %}
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
          <a class="dropdown-item" href="{% url 'administration:profile' %}">
            <i class="ti-settings text-primary"></i>
            Settings
          </a>
          <a class="dropdown-item" href="{% url 'logout' %}">
            <i class="ti-power-off text-primary"></i>
            Logout
          </a>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
      data-toggle="offcanvas">
      <span class="icon-menu"></span>
    </button>
  </div>
</nav>
<div class="container-fluid page-body-wrapper">
  <nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="/administration">
          <i class="icon-grid menu-icon"></i>
          <span class="menu-title">Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administration:skripsi' %}">
          <i class="fa-sharp fa-solid fa-book menu-icon"></i>
          <span class="menu-title">Skripsi</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administration:journal' %}">
          <i class="fa-sharp fa-solid fa-book menu-icon"></i>
          <span class="menu-title">Jurnal</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administration:mhs' %}">
          <i class="fa-solid fa-users menu-icon"></i>
          <span class="menu-title">Pengguna</span>
        </a>
      </li>
    </ul>
  </nav>